# File: shopping-app-deployment.yaml

apiVersion: apps/v1

kind: Deployment

metadata:

  name: shopping-app

  labels:

    app: shopping-app

spec:

  replicas: 2

  selector:

    matchLabels:

      app: shopping-app

  template:

    metadata:

      labels:

        app: shopping-app

    spec:

      containers:

      - name: shopping-app

        image: radheshyampatil/shopping-app:v1

        ports:

        - containerPort: 3000
 
